# Generated by Django 5.0.6 on 2024-11-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
