# Generated by Django 5.0.6 on 2024-11-22 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_news_cover_image_remove_news_cover_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsimage',
            old_name='umage_url',
            new_name='image_url',
        ),
    ]
