# Generated by Django 5.0.6 on 2024-12-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_name_event_title_remove_event_poster_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
