# Generated by Django 5.0.6 on 2024-08-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_bio_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[('Admin1', 1), (2, 'Admin2'), (3, 'Admin3'), (4, 'Guest')], default=4),
        ),
    ]
