# Generated by Django 5.0.6 on 2024-08-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin1'), (2, 'Admin2'), (3, 'Admin3'), (4, 'Guest')], default=4),
        ),
    ]
